PaintyTestTask/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Mvc;
using PaintyTestTask.Data;
using PaintyTestTask.Entities;
using PaintyTestTask.Interfaces;
using PaintyTestTask.Interfaces.Repositories;
using PaintyTestTask.Models;

namespace PaintyTestTask.Controllers
{
    public class FriendsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IRepository<User> _repository;
        private readonly IFriendshipService _friendshipService;
        public FriendsController(IFriendshipService friendshipService, IRepository<User> repository, ApplicationDbContext context)
        {
            _friendshipService = friendshipService;
            _repository = repository;
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _context.Users.ToList();
            return View(model);
        }

    }
}

PaintyTestTask/Controllers/PicturesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PaintyTestTask.Data;
using PaintyTestTask.Entities;
using PaintyTestTask.Interfaces.Repositories;

namespace PaintyTestTask.Controllers
{
    public class PicturesController : Controller
    {
        private readonly IRepository<Picture> _repositoryPicture;
        private readonly IRepository<User> _repositoryUser;
        private readonly IWebHostEnvironment _environment;
        private readonly ApplicationDbContext _context;
        public PicturesController(IWebHostEnvironment environment, ApplicationDbContext context, IRepository<Picture> repositoryPicture, IRepository<User> repositoryUser)
        {
            _environment = environment;
            _context = context;
            _repositoryPicture = repositoryPicture;
            _repositoryUser = repositoryUser;
        }
        public IActionResult Index(Guid userId)
        {
            ViewBag.UserId = userId;
            return View("Index");
        }

        //[HttpPost]
        //public async Task<IActionResult> ProcessUploadImage(Guid userId)
        //{
            
        //}
    }
}

PaintyTestTask/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace PaintyTestTask.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PaintyTestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PaintyTestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PaintyTestTask.styles.css" asp-append-version="true" />
</head>
<body>
    @if (User.Identity.IsAuthenticated == false)
    {
        <header>

            <nav class="navbar " style="background:#fff">

                <div class="container">
                    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <img height="40" src="https://static.tildacdn.com/tild6135-3530-4630-b237-313832373331/logo.png" alt="Painty">
                    </a>
                    <div class="navbar-wrap">
                        <ul class="navbar-menu">
                            <li class="login-navbar"><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                            <li class="register-navbar"><a asp-area="" asp-controller="Account" asp-action="Register">SIGN UP</a></li>
                        </ul>
                    </div>
                </div>

            </nav>
        </header>
    }

    @if (User.Identity.IsAuthenticated)
    {
        <header>

            <nav class="navbar " style="background:#fff">

                <div class="container">
                    <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <img height="40" src="https://static.tildacdn.com/tild6135-3530-4630-b237-313832373331/logo.png" alt="Painty">
                    </a>
                    <div class="navbar-wrap">
                        <ul class="navbar-menu">
                            <li>
                                <a asp-area="" asp-controller="Profile" asp-action="Index">Профиль</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Friends" asp-action="Index">Поиск Друзей</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Pictures" asp-action="Index">Мои Фотографии</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Pictures" asp-action="Index">Загрузить Фотографию</a>
                            </li>

                            <li class="profile"><a>@User.Identity.Name</a></li>
                            <li class="register-navbar"><a asp-area="" asp-controller="Account" asp-action="Logout">LOGOUT</a></li>
                        </ul>
                    </div>
                </div>

            </nav>
        </header>
    }
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PaintyTestTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>